<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="contextPath" value="${ pageContext.request.contextPath}"/>
<!DOCTYPE html>
<html>
<head>
<title>LANGUAGEUS_USERS</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
	integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	crossorigin="anonymous"></script>
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
	integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
	crossorigin="anonymous"></script>
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="${contextPath}/css/Rcss.css">
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
	integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
	crossorigin="anonymous">
<style>
div.ctn
{
	padding-top: 80px;
	padding-bottom: 20px;
}
</style>
</head>

<body style = "background-color: orange">
  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
<ul class="navbar-nav mr-auto" id = "font">
       <li class="nav-item" onmouseover = "menu_over(this);" onmouseout = "menu_out(this);">
        <a class="nav-link" href="${contextPath}/jsp/main.jsp" >MAIN<span class="sr-only">(current)</span></a>
       <li class="nav-item active" >
        <a class="nav-link" href="${contextPath}/jsp/users.jsp" >USERS</a>
      </li>  
      <li class="nav-item" onmouseover = "menu_over(this);" onmouseout = "menu_out(this);">
        <a class="nav-link" href="${contextPath}/jsp/mentoring.jsp">MENTORING</a>
      </li>
       <li class="nav-item" onmouseover = "menu_over(this);" onmouseout = "menu_out(this);">
        <a class="nav-link"  href = "${contextPath}/jsp/contact.jsp">CONTACT</a>
      </li>
      	<li class="nav-item" onmouseover = "menu_over(this);" onmouseout = "menu_out(this);">
        <a class="nav-link"  href = "${contextPath}/jsp/rate.jsp">RATE</a>
      </li>
</ul>

         <%-- 세션이 있는 경우 --%>
         <c:if test="${ !empty user }">
            <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
               <li class="nav-item dropdown"><a
                  class="nav-item nav-link dropdown-toggle mr-md-2" href="${contextPath}/jsp/webnote.jsp"
                  id="bd-versions" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false"> ${ user.name }님 </a>
                  <div class="dropdown-menu dropdown-menu-right"
                     aria-labelledby="bd-versions">
                     <form action="${contextPath}/logout.do" method="post">
                        <button type="submit" class="dropdown-item"1>Sign out</button>
                     </form>
                  </div></li>
            </ul>
         </c:if>
	    </div>
	    </nav>
	<!-- Main -->
	<div class="ctn" id="image">
		<img src="${contextPath}/img/m_3.png">
		<!-- Speaks Selection -->
		<h1>Speaks</h1>
	</div>
	<div>
		<select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select>
	</div>
	<br>
	<div>
		<select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select>
	</div>
	<br>
	<div>
		<select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select>
	</div>
	<br>
	
	<!-- Learning Selection -->
	<h1>Learning</h1>
	<br>
	<div>
		<select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select><br><select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select><br><select name="langs[]" size="1">
			<option value="---" selected="selected">-- Choose Language --</option>
			<option value="AA">Afar</option>
			<option value="AB">Abkhazian</option>
			<option value="AF">Afrikaans</option>
			<option value="AK">Akan</option>
			<option value="AM">Amharic</option>
			<option value="AR">Arabic</option>
			<option value="AS">Assamese</option>
			<option value="AW">Awadhi</option>
			<option value="AY">Aymara</option>
			<option value="AZ">Azerbaijani</option>
			<option value="B1">Bhojpuri</option>
			<option value="B2">Maithili</option>
			<option value="BA">Bashkir</option>
			<option value="BE">Belarussian</option>
			<option value="BG">Bulgarian</option>
			<option value="BH">Bihari</option>
			<option value="BI">Bislama</option>
			<option value="BL">Balochi</option>
			<option value="BN">Bengali</option>
			<option value="BO">Tibetan</option>
			<option value="BR">Breton</option>
			<option value="CA">Catalan</option>
			<option value="CB">Cebuano</option>
			<option value="CE">Chechen</option>
			<option value="CO">Corsican</option>
			<option value="CS">Czech</option>
			<option value="CY">Welsh</option>
			<option value="DA">Danish</option>
			<option value="DE">German</option>
			<option value="DK">Dakhini</option>
			<option value="DZ">Bhutani</option>
			<option value="EL">Greek</option>
			<option value="EN">English</option>
			<option value="EO">Esperanto</option>
			<option value="ES">Spanish</option>
			<option value="ET">Estonian</option>
			<option value="EU">Basque</option>
			<option value="FA">Persian</option>
			<option value="FI">Finnish</option>
			<option value="FJ">Fiji</option>
			<option value="FO">Faeroese</option>
			<option value="FR">French</option>
			<option value="FY">Frisian</option>
			<option value="GA">Irish</option>
			<option value="GD">Scottish Gaelic</option>
			<option value="GL">Galician</option>
			<option value="GN">Guarani</option>
			<option value="GU">Gujarati</option>
			<option value="HA">Hausa</option>
			<option value="HI">Hindi</option>
			<option value="HR">Croatian</option>
			<option value="HT">Haitian Creole</option>
			<option value="HU">Hungarian</option>
			<option value="HY">Armenian</option>
			<option value="IA">Interlingua</option>
			<option value="IE">Interlingue</option>
			<option value="IK">Inupiak</option>
			<option value="IN">Indonesian</option>
			<option value="IS">Icelandic</option>
			<option value="IT">Italian</option>
			<option value="IW">Hebrew</option>
			<option value="JA">Japanese</option>
			<option value="JI">Yiddish</option>
			<option value="JW">Javanese</option>
			<option value="KA">Georgian</option>
			<option value="KB">Kabyle</option>
			<option value="KI">Konkani</option>
			<option value="KK">Kazakh</option>
			<option value="KL">Greenlandic</option>
			<option value="KM">Khmer</option>
			<option value="KN">Kannada</option>
			<option value="KO">Korean</option>
			<option value="KS">Kashmiri</option>
			<option value="KU">Kurdish</option>
			<option value="KY">Kirghiz</option>
			<option value="LA">Latin</option>
			<option value="LB">Luxembourgish</option>
			<option value="LM">Lombard</option>
			<option value="LN">Lingala</option>
			<option value="LO">Laothian</option>
			<option value="LT">Lithuanian</option>
			<option value="LV">Latvian</option>
			<option value="MG">Malagasy</option>
			<option value="MI">Maori</option>
			<option value="MK">Macedonian</option>
			<option value="ML">Malayalam</option>
			<option value="MN">Mongolian</option>
			<option value="MO">Moldavian</option>
			<option value="MR">Marathi</option>
			<option value="MS">Malay</option>
			<option value="MT">Maltese</option>
			<option value="MU">Makhuwa</option>
			<option value="MW">Marwari</option>
			<option value="MY">Burmese</option>
			<option value="NA">Nauru</option>
			<option value="NE">Nepali</option>
			<option value="NL">Dutch</option>
			<option value="NO">Norwegian</option>
			<option value="OC">Occitan</option>
			<option value="OM">Oromo</option>
			<option value="OR">Oriya</option>
			<option value="PA">Punjabi</option>
			<option value="PL">Polish</option>
			<option value="PS">Pashto</option>
			<option value="PT">Portuguese</option>
			<option value="QU">Quechua</option>
			<option value="RI">Rifian</option>
			<option value="RM">Rhaeto-Romance</option>
			<option value="RN">Kirundi</option>
			<option value="RO">Romanian</option>
			<option value="RU">Russian</option>
			<option value="RW">Kinyarwanda</option>
			<option value="SA">Sanskrit</option>
			<option value="SD">Sindhi</option>
			<option value="SG">Sangro</option>
			<option value="SH">Serbo-Croatian</option>
			<option value="SI">Sinhalese</option>
			<option value="SK">Slovak</option>
			<option value="SL">Slovenian</option>
			<option value="SM">Samoan</option>
			<option value="SN">Shona</option>
			<option value="SO">Somali</option>
			<option value="SQ">Albanian</option>
			<option value="SR">Serbian</option>
			<option value="SS">Siswati</option>
			<option value="ST">Sesotho</option>
			<option value="SU">Sundanese</option>
			<option value="SV">Swedish</option>
			<option value="SW">Swahili</option>
			<option value="TA">Tamil</option>
			<option value="TE">Telugu</option>
			<option value="TG">Tajik</option>
			<option value="TH">Thai</option>
			<option value="TI">Tigrinya</option>
			<option value="TK">Turkmen</option>
			<option value="TL">Tagalog</option>
			<option value="TM">Tuareg</option>
			<option value="TN">Setswana</option>
			<option value="TO">Tonga</option>
			<option value="TR">Turkish</option>
			<option value="TS">Tsonga</option>
			<option value="TT">Tatar</option>
			<option value="TW">Twi</option>
			<option value="TZ">Tamazight</option>
			<option value="UG">Uyghur</option>
			<option value="UK">Ukrainian</option>
			<option value="UR">Urdu</option>
			<option value="UZ">Uzbek</option>
			<option value="VI">Vietnamese</option>
			<option value="VO">Volapuk</option>
			<option value="WO">Wolof</option>
			<option value="XH">Xhosa</option>
			<option value="YO">Yoruba</option>
			<option value="ZH">Chinese</option>
			<option value="ZU">Zulu</option>
		</select>
		<textarea rows="13" cols="30" name="contents">Hello. I'm Melanie from Korea. My fav movie is STAR WARS!!! I'm here for my mentoring :D Add me!</textarea>
	</div>
	 
	<!-- Video Clip  -->
	<br>
	<video width="480" height="360" controls autoplay class="image">
		<source src="${contextPath}/img/Star Wars_ The Last Jedi Awake (_45).mp4"
			type="video/mp4">
		<object data="${contextPath}/img/Star Wars_ The Last Jedi Awake (_45).mp4"
			width="480" height="360"> </object>
	</video>

</body>
</html>